on:
  issues:
    types: opened
permissions: write-all

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: a_normal_comment
      uses: TejasvOnly/random-rickroll@v1.0
      with:
        percentage: 100

