on:
  push:
    branches:
    - master

jobs:
  code-analysis-and-testing:
    name: Code analysis and testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
    - run: flutter doctor -v

    - name: Get pub dependencies
      run: flutter pub get

    - name: Flutter analyze
      run: flutter analyze
    - name: Flutter test
      run: flutter test




# push main
# pull request on main
